# Generated by Django 5.1.7 on 2025-03-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'verbose_name_plural': 'Livros'},
        ),
    ]
