# Generated by Django 5.1.7 on 2025-03-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_hora', models.DateTimeField()),
                ('local', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('musica', 'Música'), ('palestra', 'Palestra'), ('workshop', 'Workshop')], max_length=20)),
            ],
        ),
    ]
